// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiU9EAEv3uj4n4lwF8URNFUknhZd-v1WA',
    appId: '1:970251825374:web:0962c52203e8aa15f6924f',
    messagingSenderId: '970251825374',
    projectId: 'twenty-864c6',
    authDomain: 'twenty-864c6.firebaseapp.com',
    storageBucket: 'twenty-864c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzA_9d0v73oUBNndg1xtptaAmLuOriME',
    appId: '1:970251825374:android:1dcc5c38fb2dfea2f6924f',
    messagingSenderId: '970251825374',
    projectId: 'twenty-864c6',
    storageBucket: 'twenty-864c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-SCsyfsxoUx50vY_-84Hsvy5_AHmbRl4',
    appId: '1:970251825374:ios:4630ed0575c3164cf6924f',
    messagingSenderId: '970251825374',
    projectId: 'twenty-864c6',
    storageBucket: 'twenty-864c6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-SCsyfsxoUx50vY_-84Hsvy5_AHmbRl4',
    appId: '1:970251825374:ios:4630ed0575c3164cf6924f',
    messagingSenderId: '970251825374',
    projectId: 'twenty-864c6',
    storageBucket: 'twenty-864c6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiU9EAEv3uj4n4lwF8URNFUknhZd-v1WA',
    appId: '1:970251825374:web:cf5bce51465e04b5f6924f',
    messagingSenderId: '970251825374',
    projectId: 'twenty-864c6',
    authDomain: 'twenty-864c6.firebaseapp.com',
    storageBucket: 'twenty-864c6.firebasestorage.app',
  );
}
